export const sample_foods = [
    {
        id: '1',
        name: 'Software Development',
        cookTime: '1 month',
        price: 10,
        favorite: true,
        origins: ['South Africa' , 'Gauteng'],
        stars: 4,
        imageUrl: 'dev-8.jpg',
        tags: ['Web Development', 'Frontend Development', 'Database Administrator' ,'Mobile Application Development'],
    },
    {
        id: '2',
        name: 'Database Administrator',
        cookTime: '1 month',
        price: 20,
        favorite: false,
        origins: ['South Africa', 'Gauteng'],
        stars: 4,
        imageUrl: 'dev-7.jpg',
        tags: ['Database Administrator' , 'Software Development'],
    },
    {
        id: '3',
        name: 'Web Development',
        cookTime: '1 month',
        price: 30,
        favorite: true,
        origins: ['South Africa', 'Gauteng'],
        stars: 4,
        imageUrl: 'dev-2.jpg',
        tags: ['Web Development', 'Wordpress Development', 'Software Development'], 
    },
    {
        id: '4',
        name: 'Frontend Development',
        cookTime: '1 month',
        price: 40,
        favorite: true,
        origins: ['South Africa', 'Gauteng'],
        stars: 4,
        imageUrl: 'dev-4.jpg',
        tags: ['Web Development', 'Frontend Development', 'Mobile Application Development', 'Wordpress Development' , 'Software Development'],
    },
    {
        id: '5',
        name: 'Wordpress Development',
        cookTime: '1 month',
        price: 50,
        favorite: true,
        origins: ['South Africa', 'Gauteng'],
        stars: 4,
        imageUrl: 'dev-3.jpg',
        tags: ['Web Development', 'Wordpress Development', 'Frontend Development'],
    },
    {
        id: '6',
        name: 'Mobile Application Development',
        cookTime: '1 month',
        price: 60,
        favorite: false,
        origins: ['South Africa', 'Gauteng'],
        stars: 4,
        imageUrl: 'dev-1.jpg',
        tags: ['Mobile Application Development', 'Frontend Development', 'Software Development'],
    },
]

export const sample_tags = [
    { name: 'All', count: 6},
    { name: 'Software Development', count: 4},
    { name: 'Database Administrator', count: 1},
    { name: 'Web Development', count: 2},
    { name: 'Frontend Development', count: 4},
    { name: 'Wordpress Development', count: 3},
    { name: 'Mobile Application Development', count: 3},
];